name: 'Docker Run Action (Gitea Actions support)'
description: 'Run a command in a new container'
branding:
  icon: 'align-justify'
  color: 'green'
inputs:
  image:
    description: 'Image'
    required: true
  options:
    description: 'Options'
    required: false
  run:
    description: 'Run command in container'
    required: false
  shell:
    description: 'Use a specific shell'
    required: false
    default: sh
  registry:
    description: 'Registry'
    required: false
  username:
    description: 'Username'
    required: false
  password:
    description: 'Password'
    required: false
  docker_network:
    description: 'Docker Network ID'
    default: ${{ job.container.network }}
    required: false
  mount_ws:
    description: 'Can be true/false or path to directory. If true, mounts workspace as a working directory.'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
